"""new table

Revision ID: 0b5587bb0cdf
Revises: 
Create Date: 2020-02-03 13:12:19.619489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b5587bb0cdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('s_No', sa.INTEGER(), nullable=False),
    sa.Column('pin', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('s_No'),
    sa.UniqueConstraint('pin')
    )
    # ### end Alembic commands ###
