"""updates

Revision ID: abc111eaae80
Revises: ddf22d8a5b21
Create Date: 2020-02-10 10:16:25.071937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc111eaae80'
down_revision = 'ddf22d8a5b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('s_No', sa.VARCHAR(length=13), nullable=False),
    sa.Column('pin', sa.VARCHAR(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pin'),
    sa.UniqueConstraint('s_No')
    )
    # ### end Alembic commands ###
