"""updates

Revision ID: ddf22d8a5b21
Revises: 0b5587bb0cdf
Create Date: 2020-02-05 10:21:22.686658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf22d8a5b21'
down_revision = '0b5587bb0cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('s_No', sa.INTEGER(), nullable=False),
    sa.Column('pin', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('s_No'),
    sa.UniqueConstraint('pin')
    )
    # ### end Alembic commands ###
